baseURL = "https://electron.guide/"
languageCode = "en-us"
title = "electron.guide"
googleAnalytics = "UA-141764204-1"
theme = "hexohugoincubator"
staticDir = ["static"]
publishDir = "docs"
pygmentsCodeFences = true
pygmentsStyle = "manni" 
author = "rocketlaunchr.cloud"

disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[outputFormats]
[outputs]
    home = [ "HTML", "JSON", "RSS"]
    page = [ "HTML" ]


[params]
	adSense = "ca-pub-5444136912913928"
	copyrightHolder = "rocketlaunchr.cloud"
	copyrightLink = "https://rocketlaunchr.cloud"
	disqusID= "electron-guide"